### ISSUE TITLE
[2.0 Beta 5] MC 1.11.2 Crash with Voidcraft Disabled

### ISSUE THREAD

**Issue by SjetCraft** [Sunconure11/compitum-magia-issues#3] opened 2017-07-19 23:48 UTC
https://gist.github.com/SjetCraft/a064175090cf304456d49a962b13ca6d

**Comment by SjetCraft** [comment] 2017-07-19 23:56
Reccurent Complex, IvToolkit and Roguelike Dungeons disabled
https://gist.github.com/SjetCraft/fc8d80d1c5725b84f83062c6b5a9a947

**Comment by SjetCraft** [comment] 2017-07-20 00:10
TaN Disabled
https://gist.github.com/SjetCraft/8a0525aa46aba6e0e2d88cd5768aae35

**Comment by Sunconure11** [comment] 2017-08-07 01:53
As this was caused by Mystcraft, and all reports have been sent, I will close this. I will add back Mystcraft once it is a bit more optimized.

**Closed as completed by Sunconure11** 2017-08-07 01:53 UTC
Labels: Waiting on mod author, Bug, 1.11.2
